"""Offline joke bank EXPANSION (Phase 10, workstream D1).

740 NEW hand-written jokes across the same 10 categories as jokes.py
(tech, programming, desi, dad, oneliners, science, food, work, animals,
school), 74 per category. Family-friendly: no profanity, nothing
offensive, nothing punching down. Varied styles: one-liners, puns,
Q&A, short tech jokes.

Same element shape as jokes.py: {"id": str, "category": str, "text": str}.
IDs continue jokes.py's j001..j260 sequence (j261..j1000), so a merge is
collision-free.

Merge (done by parent, not here):
    from jarvis.tools.dynamic.jokes import JOKES
    from jarvis.tools.dynamic.jokes_extra import JOKES_EXTRA
    JOKES.extend(JOKES_EXTRA)   # or JOKES = JOKES + JOKES_EXTRA
then rebuild _BY_ID / _BY_CATEGORY in jokes.py.

No duplicates: every text was checked against jokes.py's bank and within
this file (see tests/unit/test_phase10_jokes.py).
"""
from __future__ import annotations

JOKES_EXTRA: list[dict] = [
    # --- tech (j261-j334) ---
    {"id": "j261", "category": "tech", "text": "My phone's facial recognition stopped recognizing me before coffee. Honestly, fair."},
    {"id": "j262", "category": "tech", "text": "I dropped my phone and it landed face-down, unbroken. My heart can't say the same."},
    {"id": "j263", "category": "tech", "text": "My smartwatch counted steps while I was napping. Even it knows I move more in my dreams."},
    {"id": "j264", "category": "tech", "text": "I have 47 tabs open. At this point I'm not browsing, I'm curating a digital museum."},
    {"id": "j265", "category": "tech", "text": "My calendar reminded me about the meeting during the meeting. Revolutionary."},
    {"id": "j266", "category": "tech", "text": "The cloud backed up my files, my photos, and apparently my shame. Two hundred gigabytes of it."},
    {"id": "j267", "category": "tech", "text": "Autocorrect changed my password mid-typing and now I'm locked out of being myself."},
    {"id": "j268", "category": "tech", "text": "I asked my smart speaker for the weather. It rained on my parade."},
    {"id": "j269", "category": "tech", "text": "My earbuds are so small I spend half my life searching for them. The other half is spent searching for my keys."},
    {"id": "j270", "category": "tech", "text": "The WiFi name at my dentist's office is This Hurts Less. Bold claim."},
    {"id": "j271", "category": "tech", "text": "I turned off read receipts. My relationships improved by at least thirty percent."},
    {"id": "j272", "category": "tech", "text": "My phone has a dark side: the camera roll at 2 a.m."},
    {"id": "j273", "category": "tech", "text": "I love my noise-canceling headphones. I can ignore people in high definition."},
    {"id": "j274", "category": "tech", "text": "My laptop is so old it runs on nostalgia and duct tape."},
    {"id": "j275", "category": "tech", "text": "I tried a digital detox. I lasted until the first traffic light."},
    {"id": "j276", "category": "tech", "text": "My streaming service asked if I was still watching, and I felt personally attacked."},
    {"id": "j277", "category": "tech", "text": "The smart fridge ordered milk by itself. It's more of an adult than I am."},
    {"id": "j278", "category": "tech", "text": "My phone storage is full. I deleted one app and gained nothing. Technology."},
    {"id": "j279", "category": "tech", "text": "I set my alarm to a gentle chime. It sounds like betrayal at 6 a.m."},
    {"id": "j280", "category": "tech", "text": "My keyboard's spacebar sticks, so now every sentence is a runon sentence."},
    {"id": "j281", "category": "tech", "text": "I asked the GPS for the fastest route. It sent me through a life lesson."},
    {"id": "j282", "category": "tech", "text": "My phone's predictive text thinks it knows me better than I do. It's right."},
    {"id": "j283", "category": "tech", "text": "I bought a phone case for protection. It protects the phone. Nothing protects my wallet."},
    {"id": "j284", "category": "tech", "text": "The robot vacuum mapped my house and judged my floor plan silently."},
    {"id": "j285", "category": "tech", "text": "My smart doorbell shows me who's there. It's always packages for someone else."},
    {"id": "j286", "category": "tech", "text": "I have a folder called Misc that contains the entirety of my existence."},
    {"id": "j287", "category": "tech", "text": "My computer asks me to prove I'm not a robot by clicking traffic lights. Bold of a robot to ask."},
    {"id": "j288", "category": "tech", "text": "The password rules want uppercase, lowercase, a number, a symbol, and a blood sacrifice."},
    {"id": "j289", "category": "tech", "text": "My phone brightness auto-adjusts to match my future: dim."},
    {"id": "j290", "category": "tech", "text": "I named my hotspot FBI Surveillance Van as a joke. The neighbor's kid still connects."},
    {"id": "j291", "category": "tech", "text": "My tablet's battery swelled up. Even my electronics have body image issues."},
    {"id": "j292", "category": "tech", "text": "The group chat has three thousand messages. I just reply lol to survive."},
    {"id": "j293", "category": "tech", "text": "My smart lights flicker when the WiFi dies, so the outage announces itself dramatically."},
    {"id": "j294", "category": "tech", "text": "I cleared my browser history out of embarrassment. The embarrassment was remembering why I opened those tabs."},
    {"id": "j295", "category": "tech", "text": "My phone fell in water and now it only speaks in bubbles."},
    {"id": "j296", "category": "tech", "text": "The office WiFi password changes weekly. I have trust issues with IT."},
    {"id": "j297", "category": "tech", "text": "My earbuds case says charging, but we both know it's just resting."},
    {"id": "j298", "category": "tech", "text": "I archived five hundred emails. Zero were important. All of them felt important."},
    {"id": "j299", "category": "tech", "text": "My TV remote has a streaming button but no stop-judging-me button."},
    {"id": "j300", "category": "tech", "text": "The app asked me to rate it. I gave it one star for asking."},
    {"id": "j301", "category": "tech", "text": "The weather app says it feels like forty degrees. It feels like betrayal."},
    {"id": "j302", "category": "tech", "text": "I plugged in my charger at one percent and watched it rise like a tiny sunrise."},
    {"id": "j303", "category": "tech", "text": "My search history is a documentary about my decline."},
    {"id": "j304", "category": "tech", "text": "The printer's first page is always a test page. Even the printer doesn't trust itself."},
    {"id": "j305", "category": "tech", "text": "My smart speaker started playing music on its own. It's either haunted or has great taste."},
    {"id": "j306", "category": "tech", "text": "I have more saved WiFi networks than friends."},
    {"id": "j307", "category": "tech", "text": "My phone screen cracked in a pattern that's genuinely artistic. Gallery material."},
    {"id": "j308", "category": "tech", "text": "The cloud says my files are synced. I believe it the way I believed the dog about the couch."},
    {"id": "j309", "category": "tech", "text": "My laptop charger is held together by hope and electrical tape."},
    {"id": "j310", "category": "tech", "text": "I asked the voice assistant to define irony. It defined it as my life."},
    {"id": "j311", "category": "tech", "text": "My phone's step counter gave up on me and just shows dashes now."},
    {"id": "j312", "category": "tech", "text": "The smart lock updated its firmware and now I'm locked out of my own house. Progress."},
    {"id": "j313", "category": "tech", "text": "I have twelve streaming subscriptions and still watch the same show on loop."},
    {"id": "j314", "category": "tech", "text": "My keyboard lights up like a spaceship. It makes my emails feel important."},
    {"id": "j315", "category": "tech", "text": "The spam folder is the most honest place on the internet. Everything there knows it's garbage."},
    {"id": "j316", "category": "tech", "text": "My phone buzzed. It was a notification about a notification."},
    {"id": "j317", "category": "tech", "text": "I set my ringtone to silence and now I miss everything peacefully."},
    {"id": "j318", "category": "tech", "text": "The GPS said turn left in two hundred meters and I've never felt more micromanaged."},
    {"id": "j319", "category": "tech", "text": "My laptop's webcam cover has seen nothing, and I intend to keep it that way."},
    {"id": "j320", "category": "tech", "text": "I bought cloud storage for my photos. The photos are of food. The cloud is disappointed."},
    {"id": "j321", "category": "tech", "text": "Do-not-disturb mode is the most used feature of my adult life."},
    {"id": "j322", "category": "tech", "text": "The smart mirror complimented my outfit. Now I trust technology completely."},
    {"id": "j323", "category": "tech", "text": "I have two hundred apps and use exactly seven of them. The rest are digital houseplants."},
    {"id": "j324", "category": "tech", "text": "My Bluetooth connected to a speaker across the street. My music is now a neighborhood issue."},
    {"id": "j325", "category": "tech", "text": "The app asked for my location to improve my experience. My experience of being watched, maybe."},
    {"id": "j326", "category": "tech", "text": "My phone died at the exact moment I needed the QR code. The universe has a sense of humor."},
    {"id": "j327", "category": "tech", "text": "I back up my files to an external drive. The drive backs up nothing but my anxiety."},
    {"id": "j328", "category": "tech", "text": "The AI wrote me a workout plan. It assumed I could run. Bold."},
    {"id": "j329", "category": "tech", "text": "My screen protector is cracked but the screen is fine. A true martyr."},
    {"id": "j330", "category": "tech", "text": "The smart bulb changed color on its own. I choose to believe it's festive."},
    {"id": "j331", "category": "tech", "text": "I got a notification that my data plan is almost gone. It went the way of my motivation."},
    {"id": "j332", "category": "tech", "text": "My phone's camera has portrait mode. It makes my chaos look intentional."},
    {"id": "j333", "category": "tech", "text": "The email said no reply, so I replied. It bounced. Even the inbox has boundaries."},
    {"id": "j334", "category": "tech", "text": "My charging cable only works at a thirty-seven-degree angle. It's a relationship built on compromise."},
    # --- programming (j335-j408) ---
    {"id": "j335", "category": "programming", "text": "I told a joke about JSON. Nobody got it. It was missing a comma."},
    {"id": "j336", "category": "programming", "text": "Why did the programmer get stuck in the shower? The instructions said lather, rinse, repeat."},
    {"id": "j337", "category": "programming", "text": "My function takes no arguments. Just like my life choices."},
    {"id": "j338", "category": "programming", "text": "Python is the only snake that won't bite. It just throws exceptions."},
    {"id": "j339", "category": "programming", "text": "I named my variables after my exes: undefined and null."},
    {"id": "j340", "category": "programming", "text": "A regex a day keeps the readability away."},
    {"id": "j341", "category": "programming", "text": "My API returned a 404: sense of humor not found."},
    {"id": "j342", "category": "programming", "text": "Why do backend devs make great detectives? They always follow the stack trace."},
    {"id": "j343", "category": "programming", "text": "I tried to catch my exception, but it was already thrown. Story of my career."},
    {"id": "j344", "category": "programming", "text": "My code passed all tests on the first run. Then I woke up from the dream."},
    {"id": "j345", "category": "programming", "text": "Commit messages from a tired dev: fixed it lol, ok now, it was the semicolon."},
    {"id": "j346", "category": "programming", "text": "Two threads walk into a bar. Deadlock."},
    {"id": "j347", "category": "programming", "text": "My recursive function called itself so many times it started asking about its childhood."},
    {"id": "j348", "category": "programming", "text": "I wrote a sorting algorithm for my priorities. It returned an empty list."},
    {"id": "j349", "category": "programming", "text": "The bug only appears in production. It's a feature of the deployment environment."},
    {"id": "j350", "category": "programming", "text": "Why did the developer bring a shovel to the code review? To dig through the technical debt."},
    {"id": "j351", "category": "programming", "text": "My linter and I have an agreement: it judges, I ignore."},
    {"id": "j352", "category": "programming", "text": "I asked the senior dev for advice. He said delete it and rewrite. He says that about everything."},
    {"id": "j353", "category": "programming", "text": "The database went down at 3 a.m. My pager has trust issues now."},
    {"id": "j354", "category": "programming", "text": "Why do programmers love nature walks? All the trees."},
    {"id": "j355", "category": "programming", "text": "My CI pipeline failed on a Friday. The weekend is cancelled."},
    {"id": "j356", "category": "programming", "text": "I refactored the code and introduced three new bugs. That's called job security."},
    {"id": "j357", "category": "programming", "text": "The QA team found a bug in my impossible-to-break feature. The feature has been humbled."},
    {"id": "j358", "category": "programming", "text": "Why did the array go to therapy? It had too many unresolved indexes."},
    {"id": "j359", "category": "programming", "text": "My code is self-documenting. Unfortunately, it documents my confusion."},
    {"id": "j360", "category": "programming", "text": "I used AI to write my code. Now the bugs are smarter than me."},
    {"id": "j361", "category": "programming", "text": "The legacy code has no comments. The comments live in the previous dev's heart."},
    {"id": "j362", "category": "programming", "text": "Why did the object go to the party alone? It had no class."},
    {"id": "j363", "category": "programming", "text": "My pull request has been open for six months. It's practically a historical landmark."},
    {"id": "j364", "category": "programming", "text": "I wrote a function called doTheThing. It does the thing. Nobody knows what the thing is."},
    {"id": "j365", "category": "programming", "text": "The staging environment is just production with extra steps and fewer users."},
    {"id": "j366", "category": "programming", "text": "Why did the developer quit the gym? He couldn't handle the heavy lifting of production deploys."},
    {"id": "j367", "category": "programming", "text": "My password is stored in plaintext. The security team is still screaming."},
    {"id": "j368", "category": "programming", "text": "I deleted the production database by accident. On the bright side, I learned a lot."},
    {"id": "j369", "category": "programming", "text": "The code review took three days. The actual fix took three minutes."},
    {"id": "j370", "category": "programming", "text": "Why did the Boolean break up with the String? Type mismatch."},
    {"id": "j371", "category": "programming", "text": "My tests are green but my conscience is red."},
    {"id": "j372", "category": "programming", "text": "I wrote a thousand lines of code today. Tomorrow I'll delete nine hundred of them."},
    {"id": "j373", "category": "programming", "text": "The bug report says it doesn't work. Thanks. Very helpful. Five stars."},
    {"id": "j374", "category": "programming", "text": "Why did the programmer get a dog? For the pair programming."},
    {"id": "j375", "category": "programming", "text": "My merge conflict strategy is to cry and pick mine."},
    {"id": "j376", "category": "programming", "text": "I named my child Null so nobody can blame them for anything."},
    {"id": "j377", "category": "programming", "text": "The framework updated and broke everything. It's tradition at this point."},
    {"id": "j378", "category": "programming", "text": "Why did the REST API get tired? Too many endpoints, not enough rest."},
    {"id": "j379", "category": "programming", "text": "My standup update: yesterday I stared at the screen, today I'll stare at a different screen."},
    {"id": "j380", "category": "programming", "text": "I wrote a comment that says do not touch. The next dev touched it. The comment was a prophecy."},
    {"id": "j381", "category": "programming", "text": "The server is down. Have you tried turning it off and on again? I have. Twelve times."},
    {"id": "j382", "category": "programming", "text": "Why did the programmer cross the road? To get to the other side of the merge conflict."},
    {"id": "j383", "category": "programming", "text": "My keyboard's most worn key is backspace. I'm an optimist."},
    {"id": "j384", "category": "programming", "text": "I inherited a codebase from 2009. Archaeologists have asked to study it."},
    {"id": "j385", "category": "programming", "text": "The feature works in Chrome but not in Safari. We don't say the thing we're all thinking."},
    {"id": "j386", "category": "programming", "text": "Why did the developer go to the art museum? To see the abstract classes."},
    {"id": "j387", "category": "programming", "text": "My rubber duck and I solved the bug. The duck did most of the work."},
    {"id": "j388", "category": "programming", "text": "I pushed to main on a Friday. My ancestors felt the disturbance."},
    {"id": "j389", "category": "programming", "text": "The ticket says urgent. The ticket is from 2019."},
    {"id": "j390", "category": "programming", "text": "Why did the container get evicted? It had too many layers of baggage."},
    {"id": "j391", "category": "programming", "text": "My code has ninety percent test coverage. The remaining ten percent is where the demons live."},
    {"id": "j392", "category": "programming", "text": "I asked the codebase for directions. It pointed to a comment from 2015."},
    {"id": "j393", "category": "programming", "text": "The deployment succeeded. Nobody knows why. Nobody is asking."},
    {"id": "j394", "category": "programming", "text": "Sprint planning is where optimism goes to get estimated."},
    {"id": "j395", "category": "programming", "text": "My variable naming convention is whatever I feel like at 2 a.m."},
    {"id": "j396", "category": "programming", "text": "I wrote a script to automate my job. Now I watch the script do my job."},
    {"id": "j397", "category": "programming", "text": "The logs say everything is fine. The users say nothing is fine. I trust the logs less."},
    {"id": "j398", "category": "programming", "text": "Why did the frontend dev break up with the designer? Too many changes in the relationship."},
    {"id": "j399", "category": "programming", "text": "My function is five hundred lines long. It's not a function, it's a novel."},
    {"id": "j400", "category": "programming", "text": "I fixed the bug by restarting. I don't know why. I'm not paid to know why."},
    {"id": "j401", "category": "programming", "text": "The code works, don't touch it. The four most terrifying words in software."},
    {"id": "j402", "category": "programming", "text": "Why did the devops engineer bring sunscreen? For the sunny-day deploys."},
    {"id": "j403", "category": "programming", "text": "My commit history tells a story. It's a tragedy."},
    {"id": "j404", "category": "programming", "text": "I googled my own error message. Someone else had it in 2011. No solution posted."},
    {"id": "j405", "category": "programming", "text": "The meeting about the bug took longer than fixing the bug."},
    {"id": "j406", "category": "programming", "text": "Why did the integer get a raise? It kept adding value."},
    {"id": "j407", "category": "programming", "text": "My code is like my jokes: it needs explaining."},
    {"id": "j408", "category": "programming", "text": "The best code is the code you didn't have to write. The second best is the code you deleted."},
    # --- desi (j409-j482) ---
    {"id": "j409", "category": "desi", "text": "Indian moms have a superpower: they can hear a wrapper open from three rooms away."},
    {"id": "j410", "category": "desi", "text": "In India, I am on my way means I just woke up."},
    {"id": "j411", "category": "desi", "text": "The price tag says fixed price. My mom says watch me."},
    {"id": "j412", "category": "desi", "text": "Indian dads have two moods: reading the newspaper, and telling you to read the newspaper."},
    {"id": "j413", "category": "desi", "text": "At an Indian wedding, the buffet line is a contact sport."},
    {"id": "j414", "category": "desi", "text": "Khana khaya is how Indian moms say I love you."},
    {"id": "j415", "category": "desi", "text": "The auto driver asked for extra fare. I asked for a discount. We both laughed."},
    {"id": "j416", "category": "desi", "text": "Indian moms keep every plastic dabba. The container industry fears them."},
    {"id": "j417", "category": "desi", "text": "In India, the monsoon is a season, a mood, and a traffic excuse."},
    {"id": "j418", "category": "desi", "text": "Thoda sa on an Indian mom's plate means enough to feed a village."},
    {"id": "j419", "category": "desi", "text": "Indian dads read the electricity bill like they're auditing the government."},
    {"id": "j420", "category": "desi", "text": "The relative who says you have grown so tall has said it every year since 1998."},
    {"id": "j421", "category": "desi", "text": "In India, a sale is not a sale until you've bargained and told three friends."},
    {"id": "j422", "category": "desi", "text": "Indian moms can convert any plastic bag into a storage solution."},
    {"id": "j423", "category": "desi", "text": "The pressure cooker whistle is India's unofficial national anthem."},
    {"id": "j424", "category": "desi", "text": "Beta, shaadi kab karoge is the question that ends every family call."},
    {"id": "j425", "category": "desi", "text": "Indian traffic: where lane markings are decorative suggestions."},
    {"id": "j426", "category": "desi", "text": "The dad who says run the AC less has it on full blast in his own room."},
    {"id": "j427", "category": "desi", "text": "In India, the guest is God. The relative who stays a week is a test of faith."},
    {"id": "j428", "category": "desi", "text": "Indian moms diagnose everything as nazar lag gayi."},
    {"id": "j429", "category": "desi", "text": "The neighborhood aunty knows your life better than your diary does."},
    {"id": "j430", "category": "desi", "text": "Marks kitne aaye is the only small talk Indian relatives know."},
    {"id": "j431", "category": "desi", "text": "Indian dads have a separate ringtone for unknown numbers: suspicion."},
    {"id": "j432", "category": "desi", "text": "The tiffin box comes back empty, or you don't come back at all."},
    {"id": "j433", "category": "desi", "text": "In India, VIP darshan means paying extra to skip the line like everyone else."},
    {"id": "j434", "category": "desi", "text": "Indian moms save the good crockery for guests who never come."},
    {"id": "j435", "category": "desi", "text": "The cricket match is paused for no one. The match cannot wait."},
    {"id": "j436", "category": "desi", "text": "Beta, chai banao is the Indian dad's way of saying the conversation is over."},
    {"id": "j437", "category": "desi", "text": "Indian weddings have more photographers than guests."},
    {"id": "j438", "category": "desi", "text": "The auto wala always knows a shortcut. The shortcut is always longer."},
    {"id": "j439", "category": "desi", "text": "Indian moms have a sixth sense for when you're about to order food online."},
    {"id": "j440", "category": "desi", "text": "Arey, itna mehenga, says my mom, haggling with a fixed-price supermarket tag."},
    {"id": "j441", "category": "desi", "text": "In India, the queue is a theoretical concept."},
    {"id": "j442", "category": "desi", "text": "Indian dads collect TV remotes like they're endangered."},
    {"id": "j443", "category": "desi", "text": "The phrase bas do minute has started more arguments than politics."},
    {"id": "j444", "category": "desi", "text": "Indian moms feed you like you're leaving for war."},
    {"id": "j445", "category": "desi", "text": "The Indian head nod in a meeting means I'll pretend to agree and do my own thing."},
    {"id": "j446", "category": "desi", "text": "My cousin got ninety-nine percent. My mom said bas ninety-nine."},
    {"id": "j447", "category": "desi", "text": "Indian dads can sleep through a wedding band but wake up if you touch the AC remote."},
    {"id": "j448", "category": "desi", "text": "The Indian mom's purse contains safety pins, elaichi, and emergency solutions to everything."},
    {"id": "j449", "category": "desi", "text": "In India, adjust is not a word. It's a lifestyle."},
    {"id": "j450", "category": "desi", "text": "The railway platform announcement is a lullaby for the frequent traveler."},
    {"id": "j451", "category": "desi", "text": "Indian moms rate restaurants by quantity, not taste. Itna chhota portion."},
    {"id": "j452", "category": "desi", "text": "Beta, sweater pehen lo is the winter mantra of every Indian mom."},
    {"id": "j453", "category": "desi", "text": "The Indian dad's definition of exercise: walking to the car."},
    {"id": "j454", "category": "desi", "text": "In India, the festival calendar is busier than the work calendar."},
    {"id": "j455", "category": "desi", "text": "Indian moms have opinions about your hair that they will share unprompted."},
    {"id": "j456", "category": "desi", "text": "The neighborhood watch in India is just three aunties on a balcony."},
    {"id": "j457", "category": "desi", "text": "Khana thanda ho jayega is the only deadline Indian families respect."},
    {"id": "j458", "category": "desi", "text": "Indian dads give directions using landmarks that no longer exist. There used to be a tree there."},
    {"id": "j459", "category": "desi", "text": "The wedding RSVP is optional. The wedding attendance is mandatory."},
    {"id": "j460", "category": "desi", "text": "Indian moms can stretch one sabzi to feed unexpected guests. It's a superpower."},
    {"id": "j461", "category": "desi", "text": "Beta, phone mein ghuse rehte ho, says dad, watching reels at full volume."},
    {"id": "j462", "category": "desi", "text": "In India, the fan has three speeds: slow, fast, and why is it so hot."},
    {"id": "j463", "category": "desi", "text": "Indian moms don't need a doorbell. They sense guests at the gate."},
    {"id": "j464", "category": "desi", "text": "Arre yaar solves nothing but makes everything feel better."},
    {"id": "j465", "category": "desi", "text": "Indian dads treat the car's mileage like a family heirloom."},
    {"id": "j466", "category": "desi", "text": "The Indian wedding dance floor has no rules, only enthusiasm."},
    {"id": "j467", "category": "desi", "text": "Beta, paani piyo is the cure for headaches, sadness, and bad grades."},
    {"id": "j468", "category": "desi", "text": "Indian moms count backwards to make you hurry. You start running at seven."},
    {"id": "j469", "category": "desi", "text": "The pressure cooker's third whistle means mom has lost patience with the dal."},
    {"id": "j470", "category": "desi", "text": "In India, chalta hai is both an excuse and a philosophy."},
    {"id": "j471", "category": "desi", "text": "Indian dads inspect hotel rooms like they're buying the property."},
    {"id": "j472", "category": "desi", "text": "The Indian mom's tumse na ho payega is the original motivational speech."},
    {"id": "j473", "category": "desi", "text": "Beta, light band karo is the national slogan of Indian dads."},
    {"id": "j474", "category": "desi", "text": "Indian weddings: where your second cousin's opinions about your life are served with dessert."},
    {"id": "j475", "category": "desi", "text": "The Indian dad's WhatsApp forwards are a genre of literature."},
    {"id": "j476", "category": "desi", "text": "Mummy, bhookh lagi hai gets you a three-course meal in twelve minutes."},
    {"id": "j477", "category": "desi", "text": "Indian moms keep medicines that expired in 2019 just in case."},
    {"id": "j478", "category": "desi", "text": "The auto driver's meter is a work of fiction."},
    {"id": "j479", "category": "desi", "text": "In India, one minute on a call means twenty minutes."},
    {"id": "j480", "category": "desi", "text": "Indian dads fall asleep during the movie and then narrate the plot they missed."},
    {"id": "j481", "category": "desi", "text": "The Indian mom's tiffin feedback, khana kam bheja tha kya, means she wants to send you more food."},
    {"id": "j482", "category": "desi", "text": "Beta, settled ho jao is the final boss of Indian parenting."},
    # --- dad (j483-j556) ---
    {"id": "j483", "category": "dad", "text": "I told my suitcase there would be no vacation this year. Now I'm dealing with emotional baggage."},
    {"id": "j484", "category": "dad", "text": "Why don't eggs tell jokes? They'd crack each other up."},
    {"id": "j485", "category": "dad", "text": "I used to be a baker. I kneaded the dough."},
    {"id": "j486", "category": "dad", "text": "I asked the librarian for books on paranoia. She whispered: they're right behind you."},
    {"id": "j487", "category": "dad", "text": "Why did the bicycle fall over? It was two-tired."},
    {"id": "j488", "category": "dad", "text": "I told my wife she should embrace her mistakes. She hugged me."},
    {"id": "j489", "category": "dad", "text": "What do you call a factory that makes good products? A satisfactory."},
    {"id": "j490", "category": "dad", "text": "I used to work in a shoe recycling shop. It was sole-destroying."},
    {"id": "j491", "category": "dad", "text": "Why don't crabs give to charity? Because they're shellfish."},
    {"id": "j492", "category": "dad", "text": "I told the doctor I broke my arm in two places. He said stop going to those places."},
    {"id": "j493", "category": "dad", "text": "What do you call a pile of cats? A meowtain."},
    {"id": "j494", "category": "dad", "text": "I asked my dad for a joke about construction. He's still working on it."},
    {"id": "j495", "category": "dad", "text": "Why did the golfer bring two pairs of pants? In case he got a hole in one."},
    {"id": "j496", "category": "dad", "text": "My wife said I should do lunges to stay in shape. That would be a big step forward."},
    {"id": "j497", "category": "dad", "text": "What do you call a bear with no ears? A b."},
    {"id": "j498", "category": "dad", "text": "I was going to make a car joke, but it was too auto-matic."},
    {"id": "j499", "category": "dad", "text": "Why did the candle quit its job? It was burned out."},
    {"id": "j500", "category": "dad", "text": "I used to be a tailor, but I wasn't suited for it."},
    {"id": "j501", "category": "dad", "text": "What do you call a fish that wears a bowtie? Sofishticated."},
    {"id": "j502", "category": "dad", "text": "I asked the waiter for something light. He brought me a feather."},
    {"id": "j503", "category": "dad", "text": "Why did the tomato turn red? Because it saw the salad dressing."},
    {"id": "j504", "category": "dad", "text": "I told my computer I needed a break. It said I looked like I needed a backup."},
    {"id": "j505", "category": "dad", "text": "What do you call a dinosaur with an extensive vocabulary? A thesaurus."},
    {"id": "j506", "category": "dad", "text": "I wanted to be a comedian, but the joke's on me."},
    {"id": "j507", "category": "dad", "text": "Why don't melons get married? They cantaloupe."},
    {"id": "j508", "category": "dad", "text": "I told a dad joke at a party. The party ended."},
    {"id": "j509", "category": "dad", "text": "What do you call a sleeping dinosaur? A dino-snore."},
    {"id": "j510", "category": "dad", "text": "I asked the gym for a membership discount. They said the price would work me out."},
    {"id": "j511", "category": "dad", "text": "Why did the banana go to the doctor? It wasn't peeling well."},
    {"id": "j512", "category": "dad", "text": "I used to be addicted to soap. I'm clean now."},
    {"id": "j513", "category": "dad", "text": "What do you call a cow with no legs? Ground beef."},
    {"id": "j514", "category": "dad", "text": "I told my wife I wanted a tattoo of a watch. She said it would be a waste of time."},
    {"id": "j515", "category": "dad", "text": "Why did the cookie go to school? To get a little batter."},
    {"id": "j516", "category": "dad", "text": "I used to work at a calendar factory. I got fired for taking days off."},
    {"id": "j517", "category": "dad", "text": "Why did the music note go to jail? It was caught in treble."},
    {"id": "j518", "category": "dad", "text": "I told the kids a joke about the roof. It went over their heads."},
    {"id": "j519", "category": "dad", "text": "What do you call a cold dog? A chili dog."},
    {"id": "j520", "category": "dad", "text": "I asked my son what he wanted for dinner. He said something I didn't burn."},
    {"id": "j521", "category": "dad", "text": "Why did the skeleton go to the party alone? He had no body to go with."},
    {"id": "j522", "category": "dad", "text": "I used to work at a bank. It was a vault of emotions."},
    {"id": "j523", "category": "dad", "text": "What do you call a sad cup of coffee? A depresso."},
    {"id": "j524", "category": "dad", "text": "I told my wife I was going to the gym. She said don't hurt yourself carrying the remote."},
    {"id": "j525", "category": "dad", "text": "Why did the phone go to school? To improve its cell-f esteem."},
    {"id": "j526", "category": "dad", "text": "I asked the butcher for a joke. He said it was a rare one."},
    {"id": "j527", "category": "dad", "text": "What do you call a fake stone? A sham-rock."},
    {"id": "j528", "category": "dad", "text": "I used to play the triangle in a band. I was the most well-rounded member."},
    {"id": "j529", "category": "dad", "text": "Why did the broom get a raise? It swept the competition."},
    {"id": "j530", "category": "dad", "text": "I told my daughter a joke about elevators. It was an uplifting experience."},
    {"id": "j531", "category": "dad", "text": "What do you call a dog in the winter? A hot dog."},
    {"id": "j532", "category": "dad", "text": "I asked the baker for a joke. He said that's the yeast he could do."},
    {"id": "j533", "category": "dad", "text": "Why did the clock get promoted? It was always on time."},
    {"id": "j534", "category": "dad", "text": "I used to be a mime. It was hard to talk about."},
    {"id": "j535", "category": "dad", "text": "What do you call a bear in the rain? A drizzly bear."},
    {"id": "j536", "category": "dad", "text": "I told my son to stop telling dad jokes. He said the jokes were inherited. Fair point."},
    {"id": "j537", "category": "dad", "text": "Why did the lightbulb go to school? To get brighter."},
    {"id": "j538", "category": "dad", "text": "I asked the gardener for a joke. He said it was a growing concern."},
    {"id": "j539", "category": "dad", "text": "What do you call a duck that gets good grades? A wise quacker."},
    {"id": "j540", "category": "dad", "text": "I used to work in a mirror factory. I could see myself doing it forever."},
    {"id": "j541", "category": "dad", "text": "Why did the bread go to therapy? It had too much on its plate."},
    {"id": "j542", "category": "dad", "text": "I told the kids I was the fun parent. They laughed. That's the joke."},
    {"id": "j543", "category": "dad", "text": "What do you call a turtle that takes up photography? A snapper."},
    {"id": "j544", "category": "dad", "text": "I asked the mechanic for a joke. He said it was under the hood, give him a minute."},
    {"id": "j545", "category": "dad", "text": "Why did the orange stop rolling? It ran out of juice."},
    {"id": "j546", "category": "dad", "text": "I used to be a train conductor. It was a track record of success."},
    {"id": "j547", "category": "dad", "text": "What do you call a sheep with no legs? A cloud."},
    {"id": "j548", "category": "dad", "text": "I told my wife our marriage is like a fine wine. She asked if it gets better with age. I said no, it gives me a headache."},
    {"id": "j549", "category": "dad", "text": "Why did the mushroom go to the party? Because he was a fungi."},
    {"id": "j550", "category": "dad", "text": "I asked the dentist for a joke. He said brace yourself."},
    {"id": "j551", "category": "dad", "text": "What do you call a bee that can't make up its mind? A maybe."},
    {"id": "j552", "category": "dad", "text": "I used to nap professionally. I was the best at resting."},
    {"id": "j553", "category": "dad", "text": "Why did the pencil go to school? To get a little sharper."},
    {"id": "j554", "category": "dad", "text": "I told the barber a joke. It was a cut above the rest."},
    {"id": "j555", "category": "dad", "text": "What do you call a dinosaur that crashes his car? A tyrannosaurus wreck."},
    {"id": "j556", "category": "dad", "text": "I asked my kids for a Father's Day gift. They gave me silence. Best gift ever."},
    # --- oneliners (j557-j630) ---
    {"id": "j557", "category": "oneliners", "text": "I don't need Google. My wife knows everything."},
    {"id": "j558", "category": "oneliners", "text": "My diet plan: make questionable choices at questionable hours."},
    {"id": "j559", "category": "oneliners", "text": "I'm not late. Everyone else is early."},
    {"id": "j560", "category": "oneliners", "text": "My superpower is finding the one squeaky floorboard at 3 a.m."},
    {"id": "j561", "category": "oneliners", "text": "I put the pro in procrastinate and the con in confidence."},
    {"id": "j562", "category": "oneliners", "text": "Adulting is just Googling how to do things and hoping for the best."},
    {"id": "j563", "category": "oneliners", "text": "I'm not ignoring you. I'm prioritizing my peace."},
    {"id": "j564", "category": "oneliners", "text": "My plants are fake because my commitment issues are real."},
    {"id": "j565", "category": "oneliners", "text": "I don't do mornings. I do coffee and regret."},
    {"id": "j566", "category": "oneliners", "text": "My idea of exercise is running out of patience."},
    {"id": "j567", "category": "oneliners", "text": "I'm not messy. I'm creatively organized."},
    {"id": "j568", "category": "oneliners", "text": "My bank account and I have an understanding: it stays empty, I stay hopeful."},
    {"id": "j569", "category": "oneliners", "text": "I don't need therapy. I need a nap and a snack."},
    {"id": "j570", "category": "oneliners", "text": "My phone is my alarm, my camera, my wallet, and my personality."},
    {"id": "j571", "category": "oneliners", "text": "I'm not a control freak. I just know the right way to do everything."},
    {"id": "j572", "category": "oneliners", "text": "My weekend plans: absolutely nothing, aggressively."},
    {"id": "j573", "category": "oneliners", "text": "I don't have a favorite child. I have a least annoying one."},
    {"id": "j574", "category": "oneliners", "text": "My cooking is so good, the smoke alarm cheers me on."},
    {"id": "j575", "category": "oneliners", "text": "I'm not addicted to my phone. We're in a committed relationship."},
    {"id": "j576", "category": "oneliners", "text": "My idea of a balanced life: equal parts coffee and chaos."},
    {"id": "j577", "category": "oneliners", "text": "I don't make mistakes. I make unexpected plot twists."},
    {"id": "j578", "category": "oneliners", "text": "My house is clean enough to be healthy and dirty enough to be happy."},
    {"id": "j579", "category": "oneliners", "text": "I'm not lazy. I'm just highly selective about my efforts."},
    {"id": "j580", "category": "oneliners", "text": "My memory is excellent. I just choose to forget boring things."},
    {"id": "j581", "category": "oneliners", "text": "I don't need a gym. I lift emotional baggage daily."},
    {"id": "j582", "category": "oneliners", "text": "My diet starts tomorrow. It has started tomorrow for three years."},
    {"id": "j583", "category": "oneliners", "text": "I'm not antisocial. I'm selectively social."},
    {"id": "j584", "category": "oneliners", "text": "My car runs on gas and my hopes run on fumes."},
    {"id": "j585", "category": "oneliners", "text": "I don't snore. I dream loudly."},
    {"id": "j586", "category": "oneliners", "text": "My to-do list has one item: make a to-do list."},
    {"id": "j587", "category": "oneliners", "text": "I'm not old. I'm vintage with better stories."},
    {"id": "j588", "category": "oneliners", "text": "My phone battery dies faster than my New Year's resolutions."},
    {"id": "j589", "category": "oneliners", "text": "I don't have time for drama. I have time for naps."},
    {"id": "j590", "category": "oneliners", "text": "My cooking style is called whatever is about to expire."},
    {"id": "j591", "category": "oneliners", "text": "I'm not indecisive. I'm thorough."},
    {"id": "j592", "category": "oneliners", "text": "My idea of multitasking: eating while deciding what to eat next."},
    {"id": "j593", "category": "oneliners", "text": "I don't need a personal trainer. I need someone to hide my snacks."},
    {"id": "j594", "category": "oneliners", "text": "My plants died, so now I own rocks. They're thriving."},
    {"id": "j595", "category": "oneliners", "text": "I'm not a morning person. I'm barely an afternoon person."},
    {"id": "j596", "category": "oneliners", "text": "My wallet is on a diet. It's lost all its cash."},
    {"id": "j597", "category": "oneliners", "text": "I don't argue. I deliver monologues."},
    {"id": "j598", "category": "oneliners", "text": "My bed and I have a toxic relationship. I can't leave it."},
    {"id": "j599", "category": "oneliners", "text": "I'm not forgetful. I'm just full of more important things."},
    {"id": "j600", "category": "oneliners", "text": "My idea of saving money: not buying things I almost bought."},
    {"id": "j601", "category": "oneliners", "text": "I don't need luck. I need better WiFi."},
    {"id": "j602", "category": "oneliners", "text": "My cooking is experimental. The fire department is my audience."},
    {"id": "j603", "category": "oneliners", "text": "I'm not broke. I'm pre-rich."},
    {"id": "j604", "category": "oneliners", "text": "My idea of a workout: walking to the fridge during commercials."},
    {"id": "j605", "category": "oneliners", "text": "I don't have a bucket list. I have a maybe-someday list."},
    {"id": "j606", "category": "oneliners", "text": "My phone autocorrects my life choices too."},
    {"id": "j607", "category": "oneliners", "text": "I'm not a quitter. I'm a strategic retreater."},
    {"id": "j608", "category": "oneliners", "text": "My idea of cleaning: shoving everything in a closet and calling it minimalism."},
    {"id": "j609", "category": "oneliners", "text": "I don't need a map. I need someone to follow."},
    {"id": "j610", "category": "oneliners", "text": "My plants are thriving. They're plastic. I have no shame."},
    {"id": "j611", "category": "oneliners", "text": "I'm not tired. I'm on standby."},
    {"id": "j612", "category": "oneliners", "text": "My diet is ninety percent good intentions and ten percent pizza."},
    {"id": "j613", "category": "oneliners", "text": "I don't have road rage. I have road commentary."},
    {"id": "j614", "category": "oneliners", "text": "My idea of a spa day: a hot shower and nobody talking to me."},
    {"id": "j615", "category": "oneliners", "text": "I'm not a night owl. I'm a permanently exhausted pigeon."},
    {"id": "j616", "category": "oneliners", "text": "My phone knows me better than my therapist. It has more data."},
    {"id": "j617", "category": "oneliners", "text": "I don't need motivation. I need snacks."},
    {"id": "j618", "category": "oneliners", "text": "My idea of meal prep: deciding which restaurant to order from."},
    {"id": "j619", "category": "oneliners", "text": "I'm not clumsy. Gravity and I have an agreement."},
    {"id": "j620", "category": "oneliners", "text": "My wallet screams when I open it. It's dramatic."},
    {"id": "j621", "category": "oneliners", "text": "I don't have trust issues. I have verification protocols."},
    {"id": "j622", "category": "oneliners", "text": "My idea of adventure: trying a new brand of instant noodles."},
    {"id": "j623", "category": "oneliners", "text": "I'm not ignoring my responsibilities. I'm giving them space."},
    {"id": "j624", "category": "oneliners", "text": "My phone's battery and my social battery die at the same rate."},
    {"id": "j625", "category": "oneliners", "text": "I don't need a vacation. I need a new identity."},
    {"id": "j626", "category": "oneliners", "text": "My cooking is so bad, the dog orders takeout."},
    {"id": "j627", "category": "oneliners", "text": "I'm not a procrastinator. I'm a deadline enthusiast."},
    {"id": "j628", "category": "oneliners", "text": "My idea of self-care: canceling plans I never wanted to make."},
    {"id": "j629", "category": "oneliners", "text": "I don't have a green thumb. I have a brown thumb of death."},
    {"id": "j630", "category": "oneliners", "text": "My life is a series of I will do it tomorrow stacked on each other."},
    # --- science (j631-j704) ---
    {"id": "j631", "category": "science", "text": "I told a joke about the Big Bang. It was explosive."},
    {"id": "j632", "category": "science", "text": "Why did the electron go to therapy? It had too much negative energy."},
    {"id": "j633", "category": "science", "text": "My love life is like dark matter: theoretically exists, never observed."},
    {"id": "j634", "category": "science", "text": "The Doppler effect: the sound of my motivation passing me by."},
    {"id": "j635", "category": "science", "text": "Why did the geologist get married? He found someone who rocks his world."},
    {"id": "j636", "category": "science", "text": "I have a joke about gravity, but it's a bit of a letdown."},
    {"id": "j637", "category": "science", "text": "The Heisenberg uncertainty principle explains my weekend: I know where I was or what I did, not both."},
    {"id": "j638", "category": "science", "text": "Why did the biologist bring a ladder? To study high-rise ecosystems."},
    {"id": "j639", "category": "science", "text": "My diet is like a black hole: food goes in, nothing comes out."},
    {"id": "j640", "category": "science", "text": "The second law of thermodynamics: my room will never clean itself."},
    {"id": "j641", "category": "science", "text": "Why did the chemist break up with the physicist? No reaction."},
    {"id": "j642", "category": "science", "text": "I told a joke about sodium. Na."},
    {"id": "j643", "category": "science", "text": "My brain cells are like my socks: some are missing and nobody knows where they went."},
    {"id": "j644", "category": "science", "text": "Why did the astronomer break up with the astrologer? Irreconcilable star charts."},
    {"id": "j645", "category": "science", "text": "I have a theory about procrastination. I'll tell you later."},
    {"id": "j646", "category": "science", "text": "The speed of dark: how fast my motivation leaves when I see the gym."},
    {"id": "j647", "category": "science", "text": "Why did the statistician bring a ladder to the bar? The odds were stacked against him."},
    {"id": "j648", "category": "science", "text": "My sleep schedule is a quantum state: simultaneously early and late until observed."},
    {"id": "j649", "category": "science", "text": "The periodic table is just chemistry's way of saying it's complicated."},
    {"id": "j650", "category": "science", "text": "Why did the physicist go broke? He lost his momentum."},
    {"id": "j651", "category": "science", "text": "I told a joke about evolution. It adapted well."},
    {"id": "j652", "category": "science", "text": "The placebo effect: when my coffee works before I drink it."},
    {"id": "j653", "category": "science", "text": "Why did the botanist get lost? He took the root less traveled."},
    {"id": "j654", "category": "science", "text": "My attention span is like a noble gas: inert and unreactive."},
    {"id": "j655", "category": "science", "text": "The Big Bang theory: my alarm going off at 6 a.m."},
    {"id": "j656", "category": "science", "text": "Why did the scientist take up gardening? He wanted to get to the root of things."},
    {"id": "j657", "category": "science", "text": "I have a joke about the immune system, but it's still developing."},
    {"id": "j658", "category": "science", "text": "The law of diminishing returns: my productivity after lunch."},
    {"id": "j659", "category": "science", "text": "Why did the geologist break up? Too much pressure."},
    {"id": "j660", "category": "science", "text": "My brain is sixty percent water and forty percent wondering what's for dinner."},
    {"id": "j661", "category": "science", "text": "The observer effect: my plants grow better when I'm not watching. So do my problems."},
    {"id": "j662", "category": "science", "text": "Why did the chemist become a comedian? He had great delivery of punchlines and compounds."},
    {"id": "j663", "category": "science", "text": "I told a joke about tectonic plates. It was groundbreaking."},
    {"id": "j664", "category": "science", "text": "The human body is ninety-nine percent empty space. That explains my head."},
    {"id": "j665", "category": "science", "text": "Why did the mathematician refuse to argue? He didn't want to be irrational."},
    {"id": "j666", "category": "science", "text": "My motivation follows Newton's first law: it stays at rest unless acted upon by panic."},
    {"id": "j667", "category": "science", "text": "The scientific method for adults: guess, Google, give up."},
    {"id": "j668", "category": "science", "text": "Why did the biologist study the ocean? For the current events."},
    {"id": "j669", "category": "science", "text": "I have a joke about carbon dating. It's old."},
    {"id": "j670", "category": "science", "text": "The Doppler effect of adulthood: time speeds up as responsibilities approach."},
    {"id": "j671", "category": "science", "text": "Why did the physicist bring string to the lab? To tie up the loose ends of theory."},
    {"id": "j672", "category": "science", "text": "My circadian rhythm is more of a circadian suggestion."},
    {"id": "j673", "category": "science", "text": "The conservation of mass: my laundry pile never decreases, it just relocates."},
    {"id": "j674", "category": "science", "text": "Why did the chemist get hired? His references were glowing."},
    {"id": "j675", "category": "science", "text": "I told a joke about the ozone layer. It went over everyone's head."},
    {"id": "j676", "category": "science", "text": "The Fermi paradox: where is everybody? Probably stuck in traffic."},
    {"id": "j677", "category": "science", "text": "Why did the astronomer get fired? He kept spacing out."},
    {"id": "j678", "category": "science", "text": "My DNA test said I'm one hundred percent tired."},
    {"id": "j679", "category": "science", "text": "The placebo effect of Monday motivation: lasts until Tuesday."},
    {"id": "j680", "category": "science", "text": "Why did the geologist go to therapy? He had too many layers to unpack."},
    {"id": "j681", "category": "science", "text": "I have a joke about the speed of sound. You just haven't heard it yet."},
    {"id": "j682", "category": "science", "text": "The second law of thermodynamics applied to my desk: chaos increases."},
    {"id": "j683", "category": "science", "text": "Why did the biologist become a chef? He loved cell culture."},
    {"id": "j684", "category": "science", "text": "My brain runs on caffeine and questionable hypotheses."},
    {"id": "j685", "category": "science", "text": "The Heisenberg principle of parenting: you can know where your kids are or what they're doing, never both."},
    {"id": "j686", "category": "science", "text": "Why did the physicist break up with the metric system? It was too measured."},
    {"id": "j687", "category": "science", "text": "I told a joke about relativity. It was all relative."},
    {"id": "j688", "category": "science", "text": "The Big Crunch: what happens to my paycheck by the twentieth."},
    {"id": "j689", "category": "science", "text": "Why did the chemist sit by the window? For the natural elements."},
    {"id": "j690", "category": "science", "text": "My sleep debt has compound interest."},
    {"id": "j691", "category": "science", "text": "The scientific name for my weekend: Homo sapiens horizontalis."},
    {"id": "j692", "category": "science", "text": "Why did the robot go on vacation? It needed to recharge."},
    {"id": "j693", "category": "science", "text": "I have a joke about the multiverse. In another universe, it's funny."},
    {"id": "j694", "category": "science", "text": "The law of conservation of energy: my energy is neither created nor destroyed, just converted into naps."},
    {"id": "j695", "category": "science", "text": "Why did the astronomer bring a map? He was lost in space."},
    {"id": "j696", "category": "science", "text": "My metabolism is like a dial-up connection: slow and unreliable."},
    {"id": "j697", "category": "science", "text": "The placebo effect of my to-do list: writing it down feels like doing it."},
    {"id": "j698", "category": "science", "text": "Why did the physicist get a dog? For the quantum leaps of joy."},
    {"id": "j699", "category": "science", "text": "My favorite element is surprise. It's not on the table."},
    {"id": "j700", "category": "science", "text": "The Doppler effect of my paycheck: it approaches quickly and recedes faster."},
    {"id": "j701", "category": "science", "text": "Why did the researcher bring snacks? For the food for thought."},
    {"id": "j702", "category": "science", "text": "My brain's RAM is full. I need to close some tabs."},
    {"id": "j703", "category": "science", "text": "The scientific method: observe, hypothesize, experiment, conclude, nap."},
    {"id": "j704", "category": "science", "text": "Why did the atom go to school? To get a little more positive."},
    # --- food (j705-j778) ---
    {"id": "j705", "category": "food", "text": "I'm on a chocolate diet. I eat chocolate when I'm sad, happy, or breathing."},
    {"id": "j706", "category": "food", "text": "My fridge is like my life: full of leftovers and questionable decisions."},
    {"id": "j707", "category": "food", "text": "I told the pizza guy my life story. He gave me extra cheese out of pity."},
    {"id": "j708", "category": "food", "text": "Breakfast is the most important meal of the day. I eat it at noon."},
    {"id": "j709", "category": "food", "text": "My salad and I have an agreement: I look at it, it judges me."},
    {"id": "j710", "category": "food", "text": "I'm not a chef. I'm a microwave artist."},
    {"id": "j711", "category": "food", "text": "The ice cream in my freezer has seen things. Mostly me at 2 a.m."},
    {"id": "j712", "category": "food", "text": "I ordered a salad. The waiter asked if I was okay."},
    {"id": "j713", "category": "food", "text": "My coffee needs coffee before I can have coffee."},
    {"id": "j714", "category": "food", "text": "My diet is called intuitive eating. My intuition says pizza."},
    {"id": "j715", "category": "food", "text": "The fridge light is my favorite nightlight."},
    {"id": "j716", "category": "food", "text": "I don't share food. I share the experience of watching me eat."},
    {"id": "j717", "category": "food", "text": "My spice rack is just different shades of I'll figure it out."},
    {"id": "j718", "category": "food", "text": "I bought organic vegetables. They are now organic compost."},
    {"id": "j719", "category": "food", "text": "The pizza box says I deserve a break. The pizza box gets me."},
    {"id": "j720", "category": "food", "text": "I'm not lactose intolerant. I'm lactose dramatic."},
    {"id": "j721", "category": "food", "text": "My cooking is fusion: confusion and delusion."},
    {"id": "j722", "category": "food", "text": "The microwave beeps like it's proud of me. It's the only one."},
    {"id": "j723", "category": "food", "text": "I eat cake for breakfast. I'm an adult. These are the perks."},
    {"id": "j724", "category": "food", "text": "My fridge has a use-by date on my motivation."},
    {"id": "j725", "category": "food", "text": "I'm not a snacker. I'm a frequent small-meal enthusiast."},
    {"id": "j726", "category": "food", "text": "The takeout menu is my love language."},
    {"id": "j727", "category": "food", "text": "I told the waiter I was on a diet. He brought me a bigger menu out of respect."},
    {"id": "j728", "category": "food", "text": "My kitchen has two settings: smoke alarm and takeout."},
    {"id": "j729", "category": "food", "text": "I'm not picky. I just have strong opinions about food."},
    {"id": "j730", "category": "food", "text": "The coffee shop knows my order. The coffee shop knows my shame."},
    {"id": "j731", "category": "food", "text": "I eat my feelings. They're delicious."},
    {"id": "j732", "category": "food", "text": "My meal prep is just buying snacks in bulk."},
    {"id": "j733", "category": "food", "text": "The fridge is empty. The takeout apps are full. Balance."},
    {"id": "j734", "category": "food", "text": "I'm not a foodie. I'm a food enthusiast with no standards."},
    {"id": "j735", "category": "food", "text": "The recipe said serves four. I am four."},
    {"id": "j736", "category": "food", "text": "I don't need a recipe. I need a fire extinguisher."},
    {"id": "j737", "category": "food", "text": "My favorite vegetable is the french fry."},
    {"id": "j738", "category": "food", "text": "The diet starts Monday. Monday keeps getting rescheduled."},
    {"id": "j739", "category": "food", "text": "I ordered dessert first. I'm living life on the edge."},
    {"id": "j740", "category": "food", "text": "My coffee is so strong it has its own personality. It's rude."},
    {"id": "j741", "category": "food", "text": "The ice cream truck song is my national anthem."},
    {"id": "j742", "category": "food", "text": "I'm not hungry. I'm just bored with flavor options."},
    {"id": "j743", "category": "food", "text": "The buffet is my happy place and my shame place."},
    {"id": "j744", "category": "food", "text": "I eat pizza with a fork when I'm feeling fancy. Which is never."},
    {"id": "j745", "category": "food", "text": "My fridge magnets hold up my hopes and my takeout menus."},
    {"id": "j746", "category": "food", "text": "The recipe called for a pinch of salt. I used a handful. I'm a rebel."},
    {"id": "j747", "category": "food", "text": "I'm not a vegetarian. I'm a selective carnivore."},
    {"id": "j748", "category": "food", "text": "The microwave is my most used appliance. The oven is decorative."},
    {"id": "j749", "category": "food", "text": "I told the chef my food was great. He said that's the frozen section talking."},
    {"id": "j750", "category": "food", "text": "My idea of cooking: ordering food and putting it on a nice plate."},
    {"id": "j751", "category": "food", "text": "The coffee machine and I have a beautiful relationship. It's one-sided."},
    {"id": "j752", "category": "food", "text": "I'm not addicted to sugar. Sugar and I are just close."},
    {"id": "j753", "category": "food", "text": "The fridge door is my favorite reading material at midnight."},
    {"id": "j754", "category": "food", "text": "I eat leftovers with pride, and a fork straight from the container."},
    {"id": "j755", "category": "food", "text": "My diet plan: eat whatever, feel guilty, repeat."},
    {"id": "j756", "category": "food", "text": "The pizza delivery guy knows my address by heart. We're basically family."},
    {"id": "j757", "category": "food", "text": "I'm not a morning person. I'm a breakfast person."},
    {"id": "j758", "category": "food", "text": "The recipe said season to taste. I seasoned to chaos."},
    {"id": "j759", "category": "food", "text": "My kitchen scale is just for show. I measure with my heart."},
    {"id": "j760", "category": "food", "text": "I don't do diets. I do lifestyle choices that involve cake."},
    {"id": "j761", "category": "food", "text": "The ice cream is gone. I have no memory of eating it. Classic."},
    {"id": "j762", "category": "food", "text": "I'm not a chef. I'm a reheating specialist."},
    {"id": "j763", "category": "food", "text": "The barista spelled my name wrong. We're no longer friends."},
    {"id": "j764", "category": "food", "text": "I eat chocolate for the antioxidants. I'm basically a health nut."},
    {"id": "j765", "category": "food", "text": "My fridge is organized by will-eat and science-experiment."},
    {"id": "j766", "category": "food", "text": "The takeout containers have formed a civilization in my fridge."},
    {"id": "j767", "category": "food", "text": "I'm not lazy. I'm conserving energy for eating."},
    {"id": "j768", "category": "food", "text": "The recipe said let it rest. I rested. The food burned."},
    {"id": "j769", "category": "food", "text": "My favorite food group is whatever's in the fridge."},
    {"id": "j770", "category": "food", "text": "I don't need a cookbook. I need a takeout menu and low standards."},
    {"id": "j771", "category": "food", "text": "The pizza is round, the box is square, the slices are triangles. Geometry is delicious."},
    {"id": "j772", "category": "food", "text": "I'm not on a diet. I'm on a see-what-happens plan."},
    {"id": "j773", "category": "food", "text": "The coffee is decaf. My disappointment is full-strength."},
    {"id": "j774", "category": "food", "text": "I eat my vegetables. They're on top of my pizza."},
    {"id": "j775", "category": "food", "text": "My idea of portion control: eating straight from the bag so there's no evidence."},
    {"id": "j776", "category": "food", "text": "The fridge light burned out. My midnight snacking continues in the dark. Commitment."},
    {"id": "j777", "category": "food", "text": "I'm not a food critic. I'm a food enthusiast with opinions."},
    {"id": "j778", "category": "food", "text": "The last slice of pizza is mine. I've claimed it. This is law."},
    # --- work (j779-j852) ---
    {"id": "j779", "category": "work", "text": "My job description says other duties as assigned. That's the whole job."},
    {"id": "j780", "category": "work", "text": "I'm not paid enough to care this much. But here I am, caring."},
    {"id": "j781", "category": "work", "text": "The office plant is thriving. It's the only thing here with a growth plan."},
    {"id": "j782", "category": "work", "text": "My inbox is a to-do list written by other people."},
    {"id": "j783", "category": "work", "text": "I'm not a team player. I'm a solo artist in a group project."},
    {"id": "j784", "category": "work", "text": "The meeting could have been a nap."},
    {"id": "j785", "category": "work", "text": "My boss says we're a family. I didn't choose this family."},
    {"id": "j786", "category": "work", "text": "I'm not overworked. I'm under-appreciated with extra steps."},
    {"id": "j787", "category": "work", "text": "The office thermostat is controlled by someone who is never cold."},
    {"id": "j788", "category": "work", "text": "My performance review says meets expectations. My expectations were higher."},
    {"id": "j789", "category": "work", "text": "I'm not a morning person. My 9 a.m. meeting knows this."},
    {"id": "j790", "category": "work", "text": "The break room coffee is free. The therapy I need after drinking it is not."},
    {"id": "j791", "category": "work", "text": "My desk has a clean pile and a do-not-touch pile. Both are the same pile."},
    {"id": "j792", "category": "work", "text": "I'm not ignoring emails. I'm letting them mature."},
    {"id": "j793", "category": "work", "text": "The printer is out of paper. The printer is also out of patience."},
    {"id": "j794", "category": "work", "text": "My job is ten percent work and ninety percent looking busy."},
    {"id": "j795", "category": "work", "text": "I'm not late to meetings. I'm fashionably on time for the important part."},
    {"id": "j796", "category": "work", "text": "The office gossip travels faster than the WiFi."},
    {"id": "j797", "category": "work", "text": "My boss asked for my honest opinion. I gave him my polite opinion."},
    {"id": "j798", "category": "work", "text": "I'm not a workaholic. I'm a deadline enthusiast."},
    {"id": "j799", "category": "work", "text": "The elevator small talk is my least favorite part of the day."},
    {"id": "j800", "category": "work", "text": "My to-do list is longer than my lunch break."},
    {"id": "j801", "category": "work", "text": "I'm not paid to think. I'm paid to nod thoughtfully."},
    {"id": "j802", "category": "work", "text": "The office birthday cake is the highlight of my month."},
    {"id": "j803", "category": "work", "text": "My job title is fancy. My job is not."},
    {"id": "j804", "category": "work", "text": "I'm not a perfectionist. I'm a good-enough enthusiast."},
    {"id": "j805", "category": "work", "text": "The Monday morning meeting is where my weekend goes to die."},
    {"id": "j806", "category": "work", "text": "My boss says think outside the box. The box is my comfort zone."},
    {"id": "j807", "category": "work", "text": "I'm not avoiding work. I'm strategically recharging."},
    {"id": "j808", "category": "work", "text": "The office microwave smells like everyone's lunch combined."},
    {"id": "j809", "category": "work", "text": "My performance bonus is a pizza party. I'm not complaining."},
    {"id": "j810", "category": "work", "text": "I'm not a slacker. I'm a work-smarter advocate."},
    {"id": "j811", "category": "work", "text": "The HR email says exciting changes. Nothing exciting has ever followed."},
    {"id": "j812", "category": "work", "text": "My desk plant died. I replaced it with a cactus. The cactus is judging me."},
    {"id": "j813", "category": "work", "text": "I'm not overthinking. I'm thoroughly analyzing."},
    {"id": "j814", "category": "work", "text": "The office dress code is business casual. My interpretation is casual."},
    {"id": "j815", "category": "work", "text": "My boss asked me to circle back. I've been circling for weeks."},
    {"id": "j816", "category": "work", "text": "I'm not a procrastinator at work. I'm a priority manager."},
    {"id": "j817", "category": "work", "text": "The coffee machine is broken. Productivity has dropped ninety percent."},
    {"id": "j818", "category": "work", "text": "My inbox zero lasted exactly four minutes."},
    {"id": "j819", "category": "work", "text": "I'm not ignoring the deadline. I'm giving it space to breathe."},
    {"id": "j820", "category": "work", "text": "The office party is mandatory fun."},
    {"id": "j821", "category": "work", "text": "My job is secure. The building is not."},
    {"id": "j822", "category": "work", "text": "I'm not a morning meeting person. I'm barely a person before coffee."},
    {"id": "j823", "category": "work", "text": "The printer jammed. I've named it Brenda. Brenda and I have history."},
    {"id": "j824", "category": "work", "text": "My boss says great question when he doesn't know the answer."},
    {"id": "j825", "category": "work", "text": "I'm not paid overtime. I'm paid in exposure to stress."},
    {"id": "j826", "category": "work", "text": "The office air conditioning is set to arctic."},
    {"id": "j827", "category": "work", "text": "My performance review: shows up. Accurate."},
    {"id": "j828", "category": "work", "text": "I'm not a team player. I am the team."},
    {"id": "j829", "category": "work", "text": "The meeting agenda is a work of fiction."},
    {"id": "j830", "category": "work", "text": "My desk is organized chaos. Mostly chaos."},
    {"id": "j831", "category": "work", "text": "I'm not avoiding the boss. I'm maintaining professional distance."},
    {"id": "j832", "category": "work", "text": "The office snack drawer is my emergency fund."},
    {"id": "j833", "category": "work", "text": "My job description didn't mention therapist for coworkers."},
    {"id": "j834", "category": "work", "text": "I'm not lazy at work. I'm energy efficient."},
    {"id": "j835", "category": "work", "text": "The Friday afternoon slump is real and it's spectacular."},
    {"id": "j836", "category": "work", "text": "My boss asked for volunteers. I suddenly needed the bathroom."},
    {"id": "j837", "category": "work", "text": "I'm not a gossip. I'm an information sharer."},
    {"id": "j838", "category": "work", "text": "The office WiFi is slower than my career progression."},
    {"id": "j839", "category": "work", "text": "My lunch break is the best part of my job. It's also the shortest."},
    {"id": "j840", "category": "work", "text": "I'm not overworked. I'm highly utilized."},
    {"id": "j841", "category": "work", "text": "The team building exercise built nothing but resentment."},
    {"id": "j842", "category": "work", "text": "My boss says we need to talk. My heart stops."},
    {"id": "j843", "category": "work", "text": "I'm not a perfectionist. I just have high standards for naps."},
    {"id": "j844", "category": "work", "text": "The office plant is fake. My enthusiasm is also fake."},
    {"id": "j845", "category": "work", "text": "My job is like a roller coaster: thrilling for others, nauseating for me."},
    {"id": "j846", "category": "work", "text": "I'm not ignoring Slack. I'm asynchronously communicating."},
    {"id": "j847", "category": "work", "text": "Performance review season is the Hunger Games of corporate life."},
    {"id": "j848", "category": "work", "text": "My boss asked me to take ownership. I took ownership of the good stapler."},
    {"id": "j849", "category": "work", "text": "I'm not a workaholic. I'm just bad at saying no."},
    {"id": "j850", "category": "work", "text": "The office coffee tastes like regret and ambition."},
    {"id": "j851", "category": "work", "text": "My inbox is full. My motivation is empty. Balance."},
    {"id": "j852", "category": "work", "text": "I'm not quitting. I'm exploring new opportunities in my dreams."},
    # --- animals (j853-j926) ---
    {"id": "j853", "category": "animals", "text": "My cat judges me from the top of the fridge. It's her throne."},
    {"id": "j854", "category": "animals", "text": "Dogs have owners. Cats have staff."},
    {"id": "j855", "category": "animals", "text": "My dog's favorite trick: pretending he hasn't been fed."},
    {"id": "j856", "category": "animals", "text": "The cat knocked over my coffee. It was a power move."},
    {"id": "j857", "category": "animals", "text": "My goldfish has a three-second memory. We get along great."},
    {"id": "j858", "category": "animals", "text": "The dog ate my sandwich. The dog has no regrets."},
    {"id": "j859", "category": "animals", "text": "My cat sits on my laptop. It's her way of saying pay attention to me."},
    {"id": "j860", "category": "animals", "text": "The parrot learned to say no. It's the most honest member of the family."},
    {"id": "j861", "category": "animals", "text": "My dog barks at the mailman. The mailman brings bills. The dog is a hero."},
    {"id": "j862", "category": "animals", "text": "The cat brings me dead mice. It's love, in cat language."},
    {"id": "j863", "category": "animals", "text": "My hamster runs on the wheel all night. He's training for something."},
    {"id": "j864", "category": "animals", "text": "The dog's guilty face is Oscar-worthy."},
    {"id": "j865", "category": "animals", "text": "My cat has nine lives. She's used three on my cooking."},
    {"id": "j866", "category": "animals", "text": "The fish tank is the most peaceful place in the house. The fish agree."},
    {"id": "j867", "category": "animals", "text": "My dog knows twenty tricks. His favorite is ignore."},
    {"id": "j868", "category": "animals", "text": "The cat's purr is the sound of a tiny engine of contentment."},
    {"id": "j869", "category": "animals", "text": "My rabbit thumps when annoyed. It's the cutest protest."},
    {"id": "j870", "category": "animals", "text": "The dog's tail wags so hard his whole body moves. Enthusiasm incarnate."},
    {"id": "j871", "category": "animals", "text": "My cat's favorite spot: wherever I'm trying to work."},
    {"id": "j872", "category": "animals", "text": "The bird sings at 5 a.m. The bird has no concept of weekends."},
    {"id": "j873", "category": "animals", "text": "My dog's bark is worse than his bite. His bite is nonexistent. He's a lover."},
    {"id": "j874", "category": "animals", "text": "The cat's midnight zoomies are a nightly marathon."},
    {"id": "j875", "category": "animals", "text": "My turtle is the wisest creature I know. He's seen things. Slowly."},
    {"id": "j876", "category": "animals", "text": "The dog's ears perk up at the word walk. It's magic."},
    {"id": "j877", "category": "animals", "text": "My cat's stare can curdle milk."},
    {"id": "j878", "category": "animals", "text": "The goldfish circles the bowl. He's either exercising or plotting."},
    {"id": "j879", "category": "animals", "text": "My dog's snoring is louder than my alarm."},
    {"id": "j880", "category": "animals", "text": "The cat's whiskers twitch when she's dreaming. I wonder what she hunts."},
    {"id": "j881", "category": "animals", "text": "My parrot mimics the phone ringing. Chaos ensues."},
    {"id": "j882", "category": "animals", "text": "The dog's puppy eyes are a weapon of mass manipulation."},
    {"id": "j883", "category": "animals", "text": "My cat's favorite toy: the box the toy came in."},
    {"id": "j884", "category": "animals", "text": "The hamster's cheeks are fuller than my savings account."},
    {"id": "j885", "category": "animals", "text": "My dog's greeting is a full-body experience."},
    {"id": "j886", "category": "animals", "text": "The cat's disdain is an art form."},
    {"id": "j887", "category": "animals", "text": "My fish recognize me. Or they recognize food. Probably food."},
    {"id": "j888", "category": "animals", "text": "The dog's zoomies after a bath are pure joy."},
    {"id": "j889", "category": "animals", "text": "My cat's paws are tiny mittens of destruction."},
    {"id": "j890", "category": "animals", "text": "The bird's vocabulary includes hello and be quiet. Balanced."},
    {"id": "j891", "category": "animals", "text": "My dog's loyalty is unmatched. My cat's loyalty is conditional."},
    {"id": "j892", "category": "animals", "text": "The rabbit's nose wiggles when happy. It's adorable."},
    {"id": "j893", "category": "animals", "text": "My cat's nap schedule is more disciplined than mine."},
    {"id": "j894", "category": "animals", "text": "The dog's favorite position: wherever the food is."},
    {"id": "j895", "category": "animals", "text": "My turtle's pace is aspirational. Slow down, enjoy the lettuce."},
    {"id": "j896", "category": "animals", "text": "The cat's tail flicks when annoyed. It's a warning system."},
    {"id": "j897", "category": "animals", "text": "My dog's bark at the vacuum is a battle cry."},
    {"id": "j898", "category": "animals", "text": "The fish's bubbles are tiny applause."},
    {"id": "j899", "category": "animals", "text": "My cat's midnight serenade is less serenade, more demand."},
    {"id": "j900", "category": "animals", "text": "The dog's nose knows when I've been eating without him."},
    {"id": "j901", "category": "animals", "text": "My parrot's laugh is contagious. And slightly evil."},
    {"id": "j902", "category": "animals", "text": "The cat's grooming is a full-time job. She's dedicated."},
    {"id": "j903", "category": "animals", "text": "My dog's ears are softer than my future."},
    {"id": "j904", "category": "animals", "text": "The rabbit's hop is pure happiness in motion."},
    {"id": "j905", "category": "animals", "text": "My cat's eyes glow in the dark. It's either cute or terrifying."},
    {"id": "j906", "category": "animals", "text": "The dog's tail is a metronome of joy."},
    {"id": "j907", "category": "animals", "text": "My fish's memory might be three seconds, but our bond is eternal."},
    {"id": "j908", "category": "animals", "text": "The cat's purr vibrates through the couch. It's healing."},
    {"id": "j909", "category": "animals", "text": "My dog's favorite game: keep-away with my sock."},
    {"id": "j910", "category": "animals", "text": "The bird's morning song is nature's alarm clock. Snooze not included."},
    {"id": "j911", "category": "animals", "text": "My cat's attitude is bigger than her body."},
    {"id": "j912", "category": "animals", "text": "The dog's loyalty card would be full by now."},
    {"id": "j913", "category": "animals", "text": "My hamster's wheel squeaks at 2 a.m. It's his mixtape."},
    {"id": "j914", "category": "animals", "text": "The cat's kneading is a massage I didn't ask for but needed."},
    {"id": "j915", "category": "animals", "text": "My dog's excitement for meals is the purest emotion."},
    {"id": "j916", "category": "animals", "text": "The fish's world is small but they seem content. Goals."},
    {"id": "j917", "category": "animals", "text": "My cat's judgment is silent but deafening."},
    {"id": "j918", "category": "animals", "text": "The dog's cuddle is the best therapy."},
    {"id": "j919", "category": "animals", "text": "My rabbit's binky is a jump of pure joy."},
    {"id": "j920", "category": "animals", "text": "The cat's independence is admirable. And slightly insulting."},
    {"id": "j921", "category": "animals", "text": "My dog's nose print on the window is modern art."},
    {"id": "j922", "category": "animals", "text": "The bird's chatter is background music for my life."},
    {"id": "j923", "category": "animals", "text": "My cat's 3 a.m. energy is unmatched and unwanted."},
    {"id": "j924", "category": "animals", "text": "The dog's dream twitches are tiny adventures."},
    {"id": "j925", "category": "animals", "text": "My fish's calm is meditative. I aspire to it."},
    {"id": "j926", "category": "animals", "text": "The cat's slow blink is the highest honor."},
    # --- school (j927-j1000) ---
    {"id": "j927", "category": "school", "text": "My backpack is heavier than my future."},
    {"id": "j928", "category": "school", "text": "The homework was due yesterday. I found out today."},
    {"id": "j929", "category": "school", "text": "My teacher's favorite phrase: this will be on the test."},
    {"id": "j930", "category": "school", "text": "The cafeteria pizza is a food group."},
    {"id": "j931", "category": "school", "text": "My locker is a black hole of forgotten assignments."},
    {"id": "j932", "category": "school", "text": "The pop quiz popped. I was not ready."},
    {"id": "j933", "category": "school", "text": "My pen ran out during the exam. The universe conspired."},
    {"id": "j934", "category": "school", "text": "The school bus is late. Again. Tradition."},
    {"id": "j935", "category": "school", "text": "My group project group did nothing. I did everything. Classic."},
    {"id": "j936", "category": "school", "text": "The teacher's handwriting is a cryptic puzzle."},
    {"id": "j937", "category": "school", "text": "My desk is wobbly. It's a metaphor for my grades."},
    {"id": "j938", "category": "school", "text": "The library is quiet. Too quiet. Suspiciously quiet."},
    {"id": "j939", "category": "school", "text": "My calculator died during math. I died inside."},
    {"id": "j940", "category": "school", "text": "The hall pass is my ticket to freedom."},
    {"id": "j941", "category": "school", "text": "My notebook is full of doodles and dreams."},
    {"id": "j942", "category": "school", "text": "The fire drill is the best part of the school day."},
    {"id": "j943", "category": "school", "text": "The teacher's disappointed look is the ultimate weapon."},
    {"id": "j944", "category": "school", "text": "The cafeteria line is longer than my patience."},
    {"id": "j945", "category": "school", "text": "My backpack zipper is broken. My life is open."},
    {"id": "j946", "category": "school", "text": "The substitute teacher doesn't know our names. Freedom."},
    {"id": "j947", "category": "school", "text": "My exam paper is blank. My mind is also blank. Symmetry."},
    {"id": "j948", "category": "school", "text": "The school bell is the sweetest sound."},
    {"id": "j949", "category": "school", "text": "My locker combination is the only number I remember."},
    {"id": "j950", "category": "school", "text": "The project group chat is ninety percent memes, ten percent work."},
    {"id": "j951", "category": "school", "text": "The teacher's quick question is never quick."},
    {"id": "j952", "category": "school", "text": "The whiteboard marker is dry. My enthusiasm is also dry."},
    {"id": "j953", "category": "school", "text": "The dog ate my homework. The dog is now educated."},
    {"id": "j954", "category": "school", "text": "The school WiFi blocks everything fun. And everything educational."},
    {"id": "j955", "category": "school", "text": "My pen is mightier than my sword. I have neither."},
    {"id": "j956", "category": "school", "text": "The teacher's we will see means no."},
    {"id": "j957", "category": "school", "text": "My backpack is a TARDIS of crumpled papers."},
    {"id": "j958", "category": "school", "text": "The exam is multiple choice. My choices are multiple regrets."},
    {"id": "j959", "category": "school", "text": "The teacher's coffee mug claims world's best. Self-awarded."},
    {"id": "j960", "category": "school", "text": "The cafeteria mystery meat remains a mystery."},
    {"id": "j961", "category": "school", "text": "My locker neighbor is loud. My locker neighbor is my friend."},
    {"id": "j962", "category": "school", "text": "The homework is done. It's just not done well."},
    {"id": "j963", "category": "school", "text": "The teacher says eyes on your own paper. My eyes wander."},
    {"id": "j964", "category": "school", "text": "The school play is a masterpiece. Of chaos."},
    {"id": "j965", "category": "school", "text": "My gym clothes smell like regret."},
    {"id": "j966", "category": "school", "text": "The library fine is higher than my allowance."},
    {"id": "j967", "category": "school", "text": "The teacher's puns are worse than mine. Impressive."},
    {"id": "j968", "category": "school", "text": "The school dance is awkward. Beautifully awkward."},
    {"id": "j969", "category": "school", "text": "My report card is a work of fiction."},
    {"id": "j970", "category": "school", "text": "The science fair volcano erupted. So did my grade."},
    {"id": "j971", "category": "school", "text": "The teacher's interesting means wrong but creative."},
    {"id": "j972", "category": "school", "text": "The cafeteria tray is a modern art piece."},
    {"id": "j973", "category": "school", "text": "My homework is in my other backpack."},
    {"id": "j974", "category": "school", "text": "The school mascot is terrifying. School spirit is fear."},
    {"id": "j975", "category": "school", "text": "The teacher's red pen is mightier than my excuses."},
    {"id": "j976", "category": "school", "text": "The pop quiz is a surprise party nobody wanted."},
    {"id": "j977", "category": "school", "text": "My locker is decorated with dreams and stickers."},
    {"id": "j978", "category": "school", "text": "The teacher's last chance is never the last chance."},
    {"id": "j979", "category": "school", "text": "My exam answers are creative writing."},
    {"id": "j980", "category": "school", "text": "The school bus driver knows all the gossip."},
    {"id": "j981", "category": "school", "text": "My notebook margins are a gallery."},
    {"id": "j982", "category": "school", "text": "The homework was optional. Nothing is optional."},
    {"id": "j983", "category": "school", "text": "The teacher's smile means trouble."},
    {"id": "j984", "category": "school", "text": "The cafeteria cookie is worth the line."},
    {"id": "j985", "category": "school", "text": "My backpack is packed. My brain is not."},
    {"id": "j986", "category": "school", "text": "The school announcement is background noise."},
    {"id": "j987", "category": "school", "text": "The teacher's good effort is a participation trophy."},
    {"id": "j988", "category": "school", "text": "The exam room is silent. My thoughts are loud."},
    {"id": "j989", "category": "school", "text": "My locker is my sanctuary."},
    {"id": "j990", "category": "school", "text": "The group project presentation is a team effort. I did the slides."},
    {"id": "j991", "category": "school", "text": "The teacher's handwriting improved. My grades didn't."},
    {"id": "j992", "category": "school", "text": "The school field trip is the highlight of the year."},
    {"id": "j993", "category": "school", "text": "My homework folder is empty. My excuse folder is full."},
    {"id": "j994", "category": "school", "text": "The teacher's any questions is a trap."},
    {"id": "j995", "category": "school", "text": "My pen collection is my pride."},
    {"id": "j996", "category": "school", "text": "The cafeteria ice cream is a rare treasure."},
    {"id": "j997", "category": "school", "text": "My backpack's weight is a workout."},
    {"id": "j998", "category": "school", "text": "The school clock ticks slower during exams."},
    {"id": "j999", "category": "school", "text": "The teacher's see me after class is ominous."},
    {"id": "j1000", "category": "school", "text": "The last day of school is the best day of the year."},
]
